openapi: 3.0.0
info:
  title: ktpro-api
  version: '2.0'
  description: Client REST API for Kegtron Pro Keg Monitors
  contact:
    email: info@kegtron.com
    name: Kegtron
    url: www.kegtron.com
servers:
  - url: 'https://mdash.net'
paths:
  /api/v2/m/device:
    get:
      summary: Device GET Endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                Example KT-420:
                  value:
                    id: device2
                    shadow:
                      state:
                        reported:
                          config:
                            afterHoursAlertEmailEna: 0
                            afterHoursAlertSmsEna: 0
                            alertEmail: user@example.com
                            alertSmsToNumber: '+15005550111'
                            autoCounterRstEna: 1
                            beaconEna: 0
                            bizHourFriDuration: 480
                            bizHourFriStart: '08:00'
                            bizHourMonDuration: 480
                            bizHourMonStart: '08:00'
                            bizHourSatDuration: 480
                            bizHourSatStart: '08:00'
                            bizHourSunDuration: 480
                            bizHourSunStart: '08:00'
                            bizHourThuDuration: 480
                            bizHourThuStart: '08:00'
                            bizHourTueDuration: 480
                            bizHourTueStart: '08:00'
                            bizHourWedDuration: 480
                            bizHourWedStart: '08:00'
                            bleEna: 0
                            cleanDetectPeriodMs: 120000
                            cleanEna: 0
                            displayUnits: 0
                            emptyThreshold: 10
                            emptyThresholdAlertEmailEna: 0
                            emptyThresholdAlertSmsEna: 0
                            lowThreshold: 20
                            lowThresholdAlertEmailEna: 0
                            lowThresholdAlertSmsEna: 0
                            port0:
                              abv: 6
                              beaconEna: 0
                              calOffset: 0
                              drinkSize: 473
                              ibu: 11
                              maker: Anheuser-Busch
                              state: 1
                              style: Malt Liquor
                              tapLabel: '1'
                              userDesc: "Don't let the smooth taste fool ya"
                              userName: King Cobra
                              volSize: 58670
                            port1:
                              abv: 4.6
                              beaconEna: 0
                              calOffset: 0
                              drinkSize: 473
                              ibu: 12
                              maker: Pabst Brewing
                              state: 1
                              style: Pale Lager - North American
                              tapLabel: '2'
                              userDesc: Tastes as great as its name
                              userName: Old Milwaukee
                              volSize: 58670
                            port2:
                              abv: 4.6
                              beaconEna: 0
                              calOffset: 0
                              drinkSize: 473
                              ibu: 13
                              maker: Pabst Brewing
                              state: 1
                              style: Pale Lager - North American
                              tapLabel: '3'
                              userDesc: The beer that made Milwaukee famous
                              userName: Schlitz
                              volSize: 29340
                            port3:
                              abv: 5.9
                              beaconEna: 0
                              calOffset: 0
                              drinkSize: 473
                              ibu: 14
                              maker: Miller Brewing
                              state: 1
                              style: Malt Liquor
                              tapLabel: '4'
                              userDesc: The King of Malt Liquor
                              userName: Olde English 800
                              volSize: 58670
                            servingMs: 5000
                            siteName: "Moe's Tavern"
                            timezone: 'PST8PDT,M3.2.0,M11.1.0'
                          config_readonly:
                            fwRev: 20200507
                            humidity: 66.5665
                            hwRev: 20200101
                            macAddr: 30AEA4426928
                            modelNum: KT-420
                            pcbRev: 1
                            port0:
                              dateCleaned: 2020/03/01
                              dateTapped: 2020/03/28
                              kFactor: 472
                              kegsServed: 1
                              lastServing: 262
                              pulseCnt: 3075
                              volDisp: 6934
                              volStart: 10376
                            port1:
                              dateCleaned: 2020/02/15
                              dateTapped: 2020/03/10
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 125
                              pulseCnt: 6862
                              volDisp: 15287
                              volStart: 58670
                            port2:
                              dateCleaned: 2020/02/05
                              dateTapped: 2020/03/20
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 652
                              pulseCnt: 5032
                              volDisp: 10650
                              volStart: 29340
                            port3:
                              dateCleaned: 2020/02/28
                              dateTapped: 2020/04/14
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 370
                              pulseCnt: 9682
                              volDisp: 20481
                              volStart: 58670
                            portCount: 4
                            serialNum: '2001011234'
                            temp: 8.2346
                          online: true
                          ota:
                            id: 867a4c0e6e721e57
                Example KT-220:
                  value:
                    id: device3
                    shadow:
                      state:
                        reported:
                          config:
                            afterHoursAlertEmailEna: 0
                            afterHoursAlertSmsEna: 0
                            alertEmail: user@example.com
                            alertSmsToNumber: '+15005550111'
                            autoCounterRstEna: 1
                            beaconEna: 0
                            bizHourFriDuration: 480
                            bizHourFriStart: '08:00'
                            bizHourMonDuration: 480
                            bizHourMonStart: '08:00'
                            bizHourSatDuration: 480
                            bizHourSatStart: '08:00'
                            bizHourSunDuration: 480
                            bizHourSunStart: '08:00'
                            bizHourThuDuration: 480
                            bizHourThuStart: '08:00'
                            bizHourTueDuration: 480
                            bizHourTueStart: '08:00'
                            bizHourWedDuration: 480
                            bizHourWedStart: '08:00'
                            bleEna: 0
                            cleanDetectPeriodMs: 120000
                            cleanEna: 0
                            displayUnits: 0
                            emptyThreshold: 10
                            emptyThresholdAlertEmailEna: 0
                            emptyThresholdAlertSmsEna: 0
                            lowThreshold: 20
                            lowThresholdAlertEmailEna: 0
                            lowThresholdAlertSmsEna: 0
                            port0:
                              abv: 5.6
                              beaconEna: 0
                              calOffset: 0
                              drinkSize: 473
                              ibu: 15
                              maker: Pabst Brewing
                              state: 1
                              style: Malt Liquor
                              tapLabel: '5'
                              userDesc: It works every time
                              userName: Colt 45
                              volSize: 58670
                            port1:
                              abv: 4.7
                              beaconEna: 0
                              calOffset: 0
                              drinkSize: 473
                              ibu: 10
                              maker: Miller Brewing
                              state: 1
                              style: Pale Lager - North American
                              tapLabel: '6'
                              userDesc: From the land of sky blue waters
                              userName: Hamms
                              volSize: 58670
                            port2:
                              abv: 0
                              beaconEna: 0
                              calOffset: 0
                              drinkSize: 473
                              ibu: 0
                              maker: ''
                              state: 0
                              style: ''
                              tapLabel: ''
                              userDesc: ''
                              userName: ''
                              volSize: 58670
                            port3:
                              abv: 0
                              beaconEna: 0
                              calOffset: 0
                              drinkSize: 473
                              ibu: 0
                              maker: ''
                              state: 0
                              style: ''
                              tapLabel: ''
                              userDesc: ''
                              userName: ''
                              volSize: 58670
                            servingMs: 5000
                            siteName: "Moe's Tavern"
                            timezone: 'PST8PDT,M3.2.0,M11.1.0'
                          config_readonly:
                            fwRev: 20200507
                            humidity: 67.0665
                            hwRev: 20200101
                            macAddr: 30AEA4CB8768
                            modelNum: KT-220
                            pcbRev: 1
                            port0:
                              dateCleaned: 2020/03/01
                              dateTapped: 2020/03/28
                              kFactor: 472
                              kegsServed: 1
                              lastServing: 262
                              pulseCnt: 3075
                              volDisp: 6934
                              volStart: 10376
                            port1:
                              dateCleaned: 2020/02/15
                              dateTapped: 2020/03/10
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 125
                              pulseCnt: 6862
                              volDisp: 15287
                              volStart: 58670
                            port2:
                              dateCleaned: ''
                              dateTapped: ''
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 0
                              pulseCnt: 0
                              volDisp: 0
                              volStart: 58670
                            port3:
                              dateCleaned: ''
                              dateTapped: ''
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 0
                              pulseCnt: 0
                              volDisp: 0
                              volStart: 58670
                            portCount: 2
                            serialNum: '2001020345'
                            temp: 8.93477
                          online: true
                          ota:
                            id: 867a4c0e6e721e57
      operationId: get-m-device
      security:
        - DEVICE_PUBLIC_KEY: []
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: content-type
          required: true
      description: "Return Device Object\n\nCalling this endpoint returns all device state information from the device shadow. \n\nNOTE:\n- Device ports are numbered 0,1,2,3 which correspond to user port numbers 1,2,3,4\n- Four port objects will always be returned\n- If shadow.state.reported.config.portCount < 4, the upper port objects can be ignored"
    post:
      summary: Device POST Endpoint
      operationId: post-m-device
      responses:
        '200':
          description: OK
      security:
        - DEVICE_PUBLIC_KEY: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                shadow:
                  type: object
                  required:
                    - state
                  properties:
                    state:
                      type: object
                      required:
                        - desired
                      properties:
                        desired:
                          type: object
                          required:
                            - config
                          properties:
                            config:
                              type: object
                              properties:
                                afterHoursAlertEmailEna:
                                  type: integer
                                afterHoursAlertSmsEna:
                                  type: integer
                                alertEmail:
                                  type: string
                                alertSmsToNumber:
                                  type: string
                                autoCounterRstEna:
                                  type: integer
                                beaconEna:
                                  type: integer
                                bizHourFriDuration:
                                  type: integer
                                bizHourFriStart:
                                  type: string
                                bizHourMonDuration:
                                  type: integer
                                bizHourMonStart:
                                  type: string
                                bizHourSatDuration:
                                  type: integer
                                bizHourSatStart:
                                  type: string
                                bizHourSunDuration:
                                  type: integer
                                bizHourSunStart:
                                  type: string
                                bizHourThuDuration:
                                  type: integer
                                bizHourThuStart:
                                  type: string
                                bizHourTueDuration:
                                  type: integer
                                bizHourTueStart:
                                  type: string
                                bizHourWedDuration:
                                  type: integer
                                bizHourWedStart:
                                  type: string
                                bleEna:
                                  type: integer
                                cleanDetectPeriodMs:
                                  type: integer
                                cleanEna:
                                  type: integer
                                displayUnits:
                                  type: integer
                                emptyThreshold:
                                  type: integer
                                emptyThresholdAlertEmailEna:
                                  type: integer
                                emptyThresholdAlertSmsEna:
                                  type: integer
                                lowThreshold:
                                  type: integer
                                lowThresholdAlertEmailEna:
                                  type: integer
                                lowThresholdAlertSmsEna:
                                  type: integer
                                port0:
                                  $ref: '#/components/schemas/port-config'
                                port1:
                                  $ref: '#/components/schemas/port-config'
                                port2:
                                  $ref: '#/components/schemas/port-config'
                                port3:
                                  $ref: '#/components/schemas/port-config'
                                servingMs:
                                  type: integer
                                siteName:
                                  type: string
                                timezone:
                                  type: string
              required:
                - shadow
        description: ''
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: content-type
          required: true
          description: ''
      description: "Update Device Shadow\n\nAny or or object keys parameters may be written to the device shadow. If the device is offline, any changes will be queued by the shadow and written to device when it is back online. "
    parameters: []
  /customer:
    get:
      summary: Customer GET Endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated_at:
                    type: string
                    description: Customer object updated date+time
                  created_at:
                    type: string
                    description: Customer object creation date+time
                  pubkeys:
                    type: object
                    required:
                      - key1
                    properties:
                      key1:
                        description: Device 1 public key
                        nullable: true
                        type: string
                      key2:
                        description: Device 2 public key
                        nullable: true
                        type: string
                      keyn:
                        description: Device n public key
                        nullable: true
                        type: string
                  token:
                    type: string
                    description: Customer token
                  email:
                    type: string
                    description: Customer email address
                  app_id:
                    type: string
                    description: mDash application id specific to Kegtron
                  id:
                    type: string
                    description: CUSTOMER_KEY
                required:
                  - updated_at
                  - created_at
                  - pubkeys
                  - token
                  - email
                  - app_id
                  - id
              examples:
                'Example: Customer with two devices':
                  value:
                    id: 2SIK4J8MhccQsflmaQP4d54
                    app_id: UCzqkgYtz91FnYAIo0uulaA
                    email: user@example.com
                    token: pKPaC1kTQ8leL3ejsY4PkFi1uYyJfAEbfjhrXpmNgsGGCgmFM8q9n
                    pubkeys:
                      LKueHqA7xsR68tdYgv4JpO: {}
                      wgpxg9Y0PQjE8U7ZNGfz9v: {}
                    created_at: '2019-12-15T23:30:07.744123249Z'
                    updated_at: '2020-02-22T02:58:12.21228205Z'
      operationId: get-customer2
      description: |-
        Return Customer Object

        The primary use for this endpoint is to obtain a list of devices and respecitve DEVICE_PUBLIC_KEYs assigned to a customer. These device keys enable GET and POST calls to the /api/v2/m/device endpoints.

        This endpoint can be called in two different ways:
        1) Use basic auth with username:password
        2) Use the CUSTOMER_KEY as the access_token

        Both methods return an identical customer object.
      security:
        - basic-auth: []
        - CUSTOMER_KEY: []
    parameters: []
  /api/v2/m/device/rpc/Kegtron.ResetVolume:
    post:
      summary: Reset Volume RPC
      operationId: post-api-v2-m-device-rpc-Kegtron.ResetVolume
      responses:
        '200':
          description: 'true'
      description: "This remote procedure call (RPC) initiates a keg volume reset on the target device for the specificed port. \n\nWhen called, the following shadow values are updated as shown:\n\n- config_readonly.porti.pulseCnt = 0\n- config_readonly.porti.volDisp = 0\n- config_readonly.porti.volStart = config.volSize\n- config_readonly.porti.dateTapped = current date"
      security:
        - DEVICE_PUBLIC_KEY: []
      parameters:
        - schema:
            type: string
            default: application-json
          in: header
          name: content-type
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                port:
                  type: integer
                  maximum: 3
                  description: 'Port number, e.g. port0, port1...'
                  minimum: 0
              required:
                - port
            examples:
              Reset port 1 (user port 2):
                value:
                  port: 1
        description: Port number 0..3 (corresponds to user port 1..4)
  /api/v2/m/device/rpc/Kegtron.ResetKegsServed:
    post:
      summary: Reset Kegs Served RPC
      operationId: post-api-v2-m-device-rpc-Kegtron.ResetKegsServed
      responses:
        '200':
          description: 'true'
      description: "This remote procedure call (RPC) initiates a reset of the kegs served counter on the target device for the specificed port. \n\nWhen called, the following shadow value is updated as shown:\n\n- config_readonly.porti.kegsServed = 0\n"
      security:
        - DEVICE_PUBLIC_KEY: []
      parameters:
        - schema:
            type: string
            default: application-json
          in: header
          name: content-type
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                port:
                  type: integer
                  maximum: 3
                  description: 'Port number, e.g. port0, port1...'
                  minimum: 0
              required:
                - port
            examples:
              Reset Port 2 (user port 3):
                value:
                  port: 2
        description: Port number 0..3 (corresponds to user port 1..4)
  /api/v2/m/device/rpc/Kegtron.UserOverride:
    post:
      summary: User Override RPC
      operationId: post-api-v2-m-device-rpc-Kegtron.UserOverride
      responses:
        '200':
          description: 'true'
      description: |
        This remote procedure call (RPC) initiates user-iniated overrides of specific shadow values on the target device for the specificed port. This method is used to prevent contention with firmware which can autonomously update these values.

        The following values can be updated via this RPC:

        - config_readonly.porti.dateTapped
        - config_readonly.porti.dateCleaned
        - config_readonly.porti.volStart
      security:
        - DEVICE_PUBLIC_KEY: []
      parameters:
        - schema:
            type: string
            default: application-json
          in: header
          name: content-type
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: object
                  required:
                    - config_readonly
                  properties:
                    config_readonly:
                      type: object
                      required:
                        - porti
                      properties:
                        porti:
                          type: object
                          description: 'Port number, e.g. port0, port1...'
                          properties:
                            dateTapped:
                              type: string
                              description: Date Format yyyy/mm/dd
                            dateCleaned:
                              type: string
                              description: Date Format yyyy/mm/dd
                            volStart:
                              type: integer
                              description: Keg starting volume in mL
              required:
                - state
            examples:
              Set Port 0 keg starting volume to 10L:
                value:
                  state:
                    config_readonly:
                      port0:
                        volStart: 10000
        description: "Replace 'i' with port number 0..3 (corresponds to user port 1..4)"
components:
  schemas:
    port-config:
      title: port-config
      type: object
      description: Port-specific configuration parameters
      properties:
        abv:
          type: number
          description: 'Alcohol By Volume value % rating'
        beaconEna:
          type: integer
          description: Enable flashing beacon for this port
        calOffset:
          type: number
          description: 'Calibration offset %'
        userName:
          type: string
          description: User description of keg attached to this port
        userDesc:
          type: string
          description: User name of keg attached to this port
        drinkSize:
          type: integer
          description: Serving volume in mL. Used for servings remaining estimation.
        ibu:
          type: integer
          description: International Bittering Units rating
        maker:
          type: string
          description: 'Beverage manufacturer (e.g. brewery, winery, etc.)'
        state:
          type: integer
          description: For future use
        style:
          type: string
          description: 'Description of beverage classification (e.g. Pilsner, Merlot, etc.)'
        tapLabel:
          type: string
          description: Customer tap handle label (usually a number)
        volSize:
          type: integer
          description: Keg volume in mL
      x-examples: {}
  securitySchemes:
    DEVICE_PUBLIC_KEY:
      name: access_token
      type: apiKey
      in: query
      description: "Insert valid 'DEVICE_PUBLIC_KEY'"
    basic-auth:
      type: http
      scheme: basic
      description: 'username:password'
    CUSTOMER_KEY:
      name: access_token
      type: apiKey
      in: query
      description: "Insert valid 'CUSTOMER_KEY'"
