openapi: 3.0.0
info:
  title: kegtron-pro
  version: '1.0'
  description: |-
    Client REST API for Kegtron Pro Keg Monitors

    Interactng with keg monitors ("devices") is a two-step process:
    1) Call the /customer endpoint to obtain list of devices and respective keys
    2) Read or write to an individual device using the /api/v2/device endpoints
  contact:
    email: info@kegtron.com
    name: Kegtron
    url: www.kegtron.com
servers:
  - url: 'https://mdash.net'
paths:
  /api/v2/m/device:
    get:
      summary: Device GET Endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example KT-420:
                  value:
                    id: devicex
                    shadow:
                      state:
                        reported:
                          config:
                            afterHoursAlertEmailEna: 0
                            afterHoursAlertSmsEna: 0
                            alertEmail: user@example.com
                            alertSmsToNumber: '+15005550111'
                            autoCounterRstEna: 0
                            beaconEna: 0
                            bizHourFriDuration: 480
                            bizHourFriStart: '08:00'
                            bizHourMonDuration: 480
                            bizHourMonStart: '08:00'
                            bizHourSatDuration: 480
                            bizHourSatStart: '08:00'
                            bizHourSunDuration: 480
                            bizHourSunStart: '08:00'
                            bizHourThuDuration: 480
                            bizHourThuStart: '08:00'
                            bizHourTueDuration: 480
                            bizHourTueStart: '08:00'
                            bizHourWedDuration: 480
                            bizHourWedStart: '08:00'
                            bleEna: 0
                            cleanDetectPeriodMs: 240000
                            cleanEna: 0
                            displayUnits: 0
                            emptyThreshold: 10
                            emptyThresholdAlertEmailEna: 0
                            emptyThresholdAlertEna: 1
                            emptyThresholdAlertSmsEna: 0
                            fwRev: 20200219
                            humidity: 79
                            hwRev: 20191213
                            lowThreshold: 20
                            lowThresholdAlertEmailEna: 0
                            lowThresholdAlertEna: 1
                            lowThresholdAlertSmsEna: 0
                            macAddr: FMRL78SMAE9C
                            modelNum: KT-420
                            pcbRev: 0
                            port0:
                              beaconEna: 0
                              calOffset: 0
                              dateCleaned: '2020-01-01'
                              dateTapped: '2019-12-25'
                              drinkSize: 473
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 120
                              pulseCnt: 57
                              state: 1
                              userDesc: Fuller’s ESB Clone
                              userName: Blue Tarp ESB
                              volDisp: 120
                              volSize: 18927
                              volStart: 9926
                            port1:
                              beaconEna: 0
                              calOffset: 0
                              dateCleaned: '2020-02-07'
                              dateTapped: '2020-02-07'
                              drinkSize: 473
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 0
                              pulseCnt: 0
                              state: 1
                              userDesc: ''
                              userName: Nuthin
                              volDisp: 0
                              volSize: 18927
                              volStart: 0
                            port2:
                              beaconEna: 0
                              calOffset: 0
                              dateCleaned: ''
                              dateTapped: '2019-10-01'
                              drinkSize: 355
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 108
                              pulseCnt: 417
                              state: 1
                              userDesc: Bavarian Wheat
                              userName: Sudwerk Hefeweizen
                              volDisp: 880
                              volSize: 19550
                              volStart: 4195
                            port3:
                              beaconEna: 0
                              calOffset: -1
                              dateCleaned: ''
                              dateTapped: 2019/12/23
                              drinkSize: 473
                              kFactor: 472
                              kegsServed: 0
                              lastServing: 421
                              pulseCnt: 517
                              state: 1
                              userDesc: Kölsch
                              userName: Früh
                              volDisp: 1082
                              volSize: 18927
                              volStart: 10110
                            portCount: 4
                            pulseTimerMs: 200
                            reportPeriodMs: 21600000
                            servingMs: 5000
                            siteName: Site Name
                            temp: 6
                            timezone: PST8
                          online: true
                          ota:
                            id: ioun6fvcfda4my86
                Example KT-220:
                  value:
                    id: devicex
                    shadow:
                      state:
                        reported:
                          config:
                            afterHoursAlertEmailEna: 0
                            afterHoursAlertSmsEna: 0
                            alertEmail: user@example.com
                            alertSmsToNumber: '+15005550111'
                            alertThreshold: 10
                            autoCounterRstEna: 1
                            beaconEna: 0
                            bizHourFriDuration: 480
                            bizHourFriStart: '08:00'
                            bizHourMonDuration: 120
                            bizHourMonStart: '20:00'
                            bizHourSatDuration: 60
                            bizHourSatStart: '08:00'
                            bizHourSunDuration: 480
                            bizHourSunStart: '08:00'
                            bizHourThuDuration: 60
                            bizHourThuStart: '12:00'
                            bizHourTueDuration: 120
                            bizHourTueStart: '08:00'
                            bizHourWedDuration: 60
                            bizHourWedStart: '20:00'
                            bleEna: 0
                            cleanDetectPeriodMs: 240000
                            cleanEna: 0
                            displayUnits: 0
                            emptyThreshold: 20
                            emptyThresholdAlertEmailEna: 0
                            emptyThresholdAlertEna: 0
                            emptyThresholdAlertSmsEna: 0
                            fwRev: 20200219
                            humidity: 2.72146e-312
                            hwRev: 20191213
                            lowThreshold: 32
                            lowThresholdAlertEmailEna: 0
                            lowThresholdAlertEna: 0
                            lowThresholdAlertSmsEna: 1
                            macAddr: 3ZLOJMHHSW4J
                            modelNum: KT-220
                            pcbRev: 1
                            port0:
                              beaconEna: 0
                              calOffset: 0
                              dateCleaned: '2020-01-05'
                              dateTapped: '2020-02-08'
                              drinkSize: 355
                              kFactor: 235
                              kegsServed: 0
                              lastServing: 0
                              pulseCnt: 0
                              state: 1
                              userDesc: Port 1
                              userName: UnoBluno
                              volDisp: 0
                              volSize: 20000
                              volStart: 5000
                            port1:
                              beaconEna: 0
                              calOffset: 0
                              dateCleaned: '2019-12-10'
                              dateTapped: 2020/02/08
                              drinkSize: 355
                              kFactor: 235
                              kegsServed: 0
                              lastServing: 0
                              pulseCnt: 0
                              state: 1
                              userDesc: Port 2
                              userName: Dos
                              volDisp: 0
                              volSize: 19550
                              volStart: 19550
                            port2:
                              beaconEna: 0
                              calOffset: 0
                              dateCleaned: ''
                              dateTapped: ''
                              drinkSize: 473
                              kFactor: 236
                              kegsServed: 0
                              lastServing: 8
                              pulseCnt: 2
                              state: 0
                              userDesc: ''
                              userName: ''
                              volDisp: 0
                              volSize: 58670
                              volStart: 58670
                            port3:
                              beaconEna: 0
                              calOffset: 0
                              dateCleaned: ''
                              dateTapped: ''
                              drinkSize: 473
                              kFactor: 236
                              kegsServed: 0
                              lastServing: 8
                              pulseCnt: 2
                              state: 0
                              userDesc: ''
                              userName: ''
                              volDisp: 0
                              volSize: 58670
                              volStart: 58670
                            portCount: 2
                            pulseTimerMs: 200
                            reportPeriodMs: 21600000
                            servingMs: 5000
                            siteName: Site Name
                            temp: 22.25
                            timezone: PST8
                            warnThreshold: 20
                          online: true
                          ota:
                            id: 4wkboymxhyzfbqqu
      operationId: get-m-device
      security:
        - DEVICE_PUBLIC_KEY: []
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: content-type
          required: true
      description: "Return Device Object\n\nCalling this endpoint returns all device state information from the device shadow. \n\nNOTE:\n- Device ports are numbered 0,1,2,3 which correspond to user port numbers 1,2,3,4\n- Four port objects will always be returned\n- If shadow.state.reported.config.portCount < 4, the upper port objects can be ignored"
    post:
      summary: Device POST Endpoint
      operationId: post-m-device
      responses:
        '200':
          description: OK
      security:
        - DEVICE_PUBLIC_KEY: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                shadow:
                  type: object
                  required:
                    - state
                  properties:
                    state:
                      type: object
                      required:
                        - desired
                      properties:
                        desired:
                          type: object
                          required:
                            - config
                          properties:
                            config:
                              type: object
                              properties:
                                afterHoursAlertEmailEna:
                                  type: integer
                                afterHoursAlertSmsEna:
                                  type: integer
                                alertSmsToNumber:
                                  type: string
                                beaconEna:
                                  type: integer
                                bizHourFriDuration:
                                  type: integer
                                bizHourFriStart:
                                  type: string
                                bizHourMonDuration:
                                  type: integer
                                bizHourMonStart:
                                  type: string
                                bizHourSatDuration:
                                  type: integer
                                bizHourSatStart:
                                  type: string
                                bizHourSunDuration:
                                  type: integer
                                bizHourSunStart:
                                  type: string
                                bizHourThuDuration:
                                  type: integer
                                bizHourThuStart:
                                  type: string
                                bizHourTueDuration:
                                  type: integer
                                bizHourTueStart:
                                  type: string
                                bizHourWedDuration:
                                  type: integer
                                bizHourWedStart:
                                  type: string
                                cleanDetectPeriodMs:
                                  type: integer
                                cleanEna:
                                  type: integer
                                displayUnits:
                                  type: integer
                                emptyThreshold:
                                  type: integer
                                emptyThresholdAlertEmailEna:
                                  type: integer
                                emptyThresholdAlertSmsEna:
                                  type: integer
                                lowThreshold:
                                  type: integer
                                lowThresholdAlertEmailEna:
                                  type: integer
                                lowThresholdAlertSmsEna:
                                  type: integer
                                port0:
                                  $ref: '#/components/schemas/port'
                                port1:
                                  $ref: '#/components/schemas/port'
                                port2:
                                  $ref: '#/components/schemas/port'
                                port3:
                                  $ref: '#/components/schemas/port'
                                reportPeriodMs:
                                  type: integer
                                servingMs:
                                  type: integer
                                siteName:
                                  type: string
                                timezone:
                                  type: string
              required:
                - shadow
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: content-type
          required: true
      description: "Update Device Shadow\n\nAny or or object keys parameters may be written to the device shadow. If the device is offline, any changes will be queued by the shadow and written to device when it is back online. "
    parameters: []
  /customer:
    get:
      summary: Customer GET Endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated_at:
                    type: string
                    description: Customer object updated date+time
                  created_at:
                    type: string
                    description: Customer object creation date+time
                  pubkeys:
                    type: object
                    required:
                      - key1
                    properties:
                      key1:
                        description: Device 1 public key
                        nullable: true
                        type: string
                      keg2:
                        description: Device 2 public key
                        nullable: true
                        type: string
                      keyn:
                        description: Device n public key
                        nullable: true
                        type: string
                  token:
                    type: string
                    description: Customer token
                  email:
                    type: string
                    description: Customer email address
                  app_id:
                    type: string
                    description: mDash application id specific to Kegtron
                  id:
                    type: string
                    description: CUSTOMER_KEY
                required:
                  - id
                  - app_id
                  - email
                  - token
                  - pubkeys
                  - created_at
                  - updated_at
              examples:
                'Example: Customer with two devices':
                  value:
                    id: 2SIK4J8MhccQsflmaQP4d54
                    app_id: UCzqkgYtz91FnYAIo0uulaA
                    email: user@example.com
                    token: pKPaC1kTQ8leL3ejsY4PkFi1uYyJfAEbfjhrXpmNgsGGCgmFM8q9n
                    pubkeys:
                      LKueHqA7xsR68tdYgv4JpO: {}
                      wgpxg9Y0PQjE8U7ZNGfz9v: {}
                    created_at: '2019-12-15T23:30:07.744123249Z'
                    updated_at: '2020-02-22T02:58:12.21228205Z'
      operationId: get-customer2
      description: |-
        Return Customer Object

        The primary use for this endpoint is to obtain a list of devices and respecitve DEVICE_PUBLIC_KEYs assigned to a customer. These device keys enable GET and POST calls to the /api/v2/m/device endpoints.
      security:
        - basic-auth: []
    parameters: []
components:
  schemas:
    port:
      title: port
      type: object
      description: Port-specific configuration parameters
      properties:
        beaconEna:
          type: integer
          description: Enable flashing beacon for this port
        calOffset:
          type: number
          description: 'Calibration offset %'
        volStart:
          type: integer
          description: Keg starting volume in mL
        volSize:
          type: integer
          description: Keg volume in mL
        userName:
          type: string
          description: User description of keg attached to this port
        userDesc:
          type: string
          description: User name of keg attached to this port
        state:
          type: integer
          description: For future use
        pulseCnt:
          type: integer
          description: Total pulses counted from flow meter since last reset
        lastServing:
          type: integer
          description: Volume of last measured serving in mL
        kegsServed:
          type: integer
          description: Count of kegs served on this port
        kFactor:
          type: integer
          description: 'Flow meter K-Factor. For factory use only. '
        drinkSize:
          type: integer
          description: Serving volume in mL. Used for servings remaining estimation.
        dateTapped:
          type: string
          description: "Date (UTC) this port's keg was last tapped"
        dateCleaned:
          type: string
          description: Date (UTC) this port was last cleaned
  securitySchemes:
    DEVICE_PUBLIC_KEY:
      name: access_token
      type: apiKey
      in: query
      description: "Insert valid 'DEVICE_PUBLIC_KEY'"
    basic-auth:
      type: http
      scheme: basic
      description: 'username:password'
